### ISSUE TITLE
Submit new signature

### ISSUE THREAD

**Issue by codefuhrer** [emposha/Shell-Detector#18]
I have a couple of webshells in my personal "zoo", and none of them was detected as shell during the test. I'd like to submit these shells to your DB, - how can i do that?

![2016-02-09 03_14_17](https://cloud.githubusercontent.com/assets/2178368/12903771/47bfb16a-cedb-11e5-8780-df67d18e7e75.png)

**Comment by emposha** [comment]
you can send them thru website http://www.shelldetector.com/#submit

**Comment by codefuhrer** [comment]
Ok, understood.
